#!/bin/bash

mysql -uroot --password='$MYSQL_ROOT_PASSWORD' <<MYSQL_SCRIPT
    CREATE DATABASE $MYSQL_DATABASE DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
MYSQL_SCRIPT

echo "Created MySQL database $MYSQL_DATABASE"

mysql -uroot --password='$MYSQL_ROOT_PASSWORD' <<MYSQL_SCRIPT
    GRANT ALL PRIVILEGES ON $MYSQL_DATABASE To '$MYSQL_USER' IDENTIFIED BY '$MYSQL_PASSWORD';
MYSQL_SCRIPT

echo "Granted all privileges on  $MYSQL_DATABASE to $MYSQL_USER"